#use official node.js image for environment
FROM node:22-alpine

#set working directory inside the continer
WORKDIR /app

#copy all packge and package-lock into workig directory
COPY package*.json ./

#install dependencies
RUN npm install

#Copy remaining files from this to container like index.js
COPY . .

ENV PORT=3000

#EXPOSE 3000

CMD ["node", "index.js"]
